### ISSUE TITLE
'Value used but not set' error

### ISSUE THREAD

**Issue by Cyb3r4rch3r** [corelight/detect-ransomware-filenames#2]
Installed on Zeek 3.3.0-dev.564 using zkg to install
All checks were fine, installed and immediately started throwing these errors in reporter.log
`{"ts":1606679832.552647,"level":"Reporter::ERROR","message":"value used but not set (checkforransomwarefilenames::ransomware_filename_patterns_paraglob)","location":"/opt/zeek/spool/installed-scripts-do-not-touch/site/packages/./detect-ransomware-filenames/./check-for-ransomware-filenames.zeek, line 69"}`
and
`{"ts":1606679382.156611,"level":"Reporter::WARNING","message":"fsrm_patterns_for_zeek.tsv/Input::READER_ASCII: Init: cannot open fsrm_patterns_for_zeek.tsv","location":""}`
Any idea what the cause may be and what the fix is?

**Comment by markoverholser** [comment]
It seems to be rooted in this issue: `Init: cannot open fsrm_patterns_for_zeek.tsv`, which means that Zeek couldn't locate or open the `fsrm_patterns_for_zeek.tsv` file which it uses to load the Paraglob instance. Where did that file end up on the filesystem? You might need to adjust the path in `check-for-ransomware-filenames.zeek`

On line 36, adjust the following:
`Input::add_table([$source="fsrm_patterns_for_zeek.tsv", $n`

To something like this:
`Input::add_table([$source="../inputs/fsrm_patterns_for_zeek.tsv", $n`

Or adjust it to use the absolute path. I'm sorry for the inconvenience, I did my tests against Zeek manually, not with `zkg`.

**Comment by Cyb3r4rch3r** [comment]
No worries and thank you! I'm unsure where it ended up as it installed via zkg, I'll give that a shot and let you know the result.

**Comment by Cyb3r4rch3r** [comment]
When installing via zkg, it placed the file in these two locations:
/home/zeek/.zkg/clones/package/detect-ransomware-filenames/inputs/fsrm_patterns_for_zeek.tsv
/home/zeek/.zkg/scratch/detect-ransomware-filenames/inputs/fsrm_patterns_for_zeek.tsv

I have moved it to the same directory as the check-for-ransomware-filenames.zeek and the errors are no longer being reported.
Thanks for the quick response!
